// GENERATED by scripts/gen-examples.mjs — do not edit.
// Source of truth is examples/*.cir.

export interface Example {
  file: string;
  label: string;
  parts: number;
  letters: string[];
  text: string;
}

export const EXAMPLES: Example[] = [
  {
    "file": "all-elements.cir",
    "label": "Every SPICE element type (A-Z)",
    "parts": 27,
    "letters": [
      "A",
      "B",
      "C",
      "D",
      "E",
      "F",
      "G",
      "H",
      "I",
      "J",
      "K",
      "L",
      "M",
      "N",
      "O",
      "P",
      "Q",
      "R",
      "S",
      "T",
      "U",
      "V",
      "W",
      "X",
      "Y",
      "Z"
    ],
    "text": "* Every SPICE element type (A-Z)\nVS in 0 DC 5\nR1 r1a r1b 1k\nC1 c1a c1b 100n\nL1 l1a l1b 10m\nL2 l2a l2b 5m\nK1 L1 L2 0.99\nD1 d1a d1b 1N4148\nQ1 qc qb qe 2N3904\nM1 md mg ms mb NMOS\nJ1 jd jg js 2N3819\nZ1 zd zg zs mesmod\nE1 eout 0 in 0 10\nG1 gout 0 in 0 1m\nF1 fout 0 VS 2\nH1 hout 0 VS 100\nB1 bout 0 V=V(in)*2\nS1 sout 0 ctrl 0 swmod\nW1 wout 0 VS swmod\nT1 t1a 0 t1b 0 Z0=50 TD=1n\nO1 o1a 0 o1b 0 lossyline\nY1 y1a 0 y1b 0 txlmod\nU1 u1a u1b 0 urcmod L=1m\nP1 pi1 pi2 0 po1 po2 0 cplmod\nX1 x1a x1b x1c opamp\nA1 in out amp\nN1 n1a n1b mynum\nI1 i1a 0 DC 1m\n.end\n"
  },
  {
    "file": "cmos-inverter.cir",
    "label": "CMOS inverter",
    "parts": 4,
    "letters": [
      "C",
      "M",
      "V"
    ],
    "text": "* CMOS inverter\nVDD vdd 0 DC 3.3\nM1 out in vdd vdd PMOS W=2u L=180n\nM2 out in 0 0 NMOS W=1u L=180n\nC1 out 0 10f\n.end\n"
  },
  {
    "file": "common-emitter.cir",
    "label": "Common emitter amplifier",
    "parts": 7,
    "letters": [
      "C",
      "Q",
      "R",
      "V"
    ],
    "text": "* Common emitter amplifier\nVCC vcc 0 DC 12\nR1 vcc b 100k\nR2 b 0 22k\nRC vcc c 4.7k\nRE e 0 1k\nQ1 c b e 2N3904\nC1 in b 10u\n.end\n"
  },
  {
    "file": "dependent-sources.cir",
    "label": "Dependent sources",
    "parts": 12,
    "letters": [
      "B",
      "E",
      "F",
      "G",
      "H",
      "R",
      "V"
    ],
    "text": "* Dependent sources\nVIN in 0 AC 1\nRIN in 0 1meg\nE1 e 0 in 0 10\nG1 g 0 in 0 1m\nRG g 0 1k\nVS s 0 DC 0\nF1 f 0 VS 2\nRF f 0 1k\nH1 h 0 VS 100\nRH h 0 1k\nB1 b 0 V=V(in)*V(in)\nRB b 0 1k\n.end\n"
  },
  {
    "file": "rc-lowpass.cir",
    "label": "RC low pass",
    "parts": 3,
    "letters": [
      "C",
      "R",
      "V"
    ],
    "text": "* RC low pass\nV1 in 0 AC 1\nR1 in out 1k\nC1 out 0 100n\n.ac dec 10 1 1meg\n.end\n"
  },
  {
    "file": "sallen-key.cir",
    "label": "Sallen-Key low pass",
    "parts": 8,
    "letters": [
      "C",
      "R",
      "V",
      "X"
    ],
    "text": "* Sallen-Key low pass\n.subckt OPAMP non_inv inv out vcc vee\nE1 out 0 table {V(non_inv)-V(inv)} = (-15 -15) (15 15)\n.ends\nVCC vcc 0 DC 15\nVEE vee 0 DC -15\nVIN in 0 AC 1\nR1 in n1 10k\nR2 n1 n2 10k\nC1 n1 out 10n\nC2 n2 0 10n\nX1 n2 out out vcc vee OPAMP\n.control\nac dec 10 1 100k\nplot 'Magnitude' vdb(out)\n.endc\n.end\n"
  },
  {
    "file": "switches.cir",
    "label": "Voltage and current controlled switches",
    "parts": 7,
    "letters": [
      "R",
      "S",
      "V",
      "W"
    ],
    "text": "* Voltage and current controlled switches\nV1 supply 0 DC 5\nVCTRL ctrl 0 PULSE(0 5 0 1n 1n 1u 2u)\nS1 supply load ctrl 0 SWMOD\nRLOAD load 0 1k\nVSENSE sense 0 DC 0\nW1 supply alt VSENSE CSWMOD\nRALT alt 0 2k\n.model SWMOD SW vt=2.5 ron=1 roff=1meg\n.end\n"
  },
  {
    "file": "transformer.cir",
    "label": "Coupled inductor transformer",
    "parts": 5,
    "letters": [
      "K",
      "L",
      "R",
      "V"
    ],
    "text": "* Coupled inductor transformer\nV1 pri 0 SIN(0 12 50)\nL1 pri 0 10m\nL2 sec 0 2.5m\nK1 L1 L2 0.98\nRL sec 0 100\n.end\n"
  },
  {
    "file": "transmission-line.cir",
    "label": "Lossless transmission line",
    "parts": 4,
    "letters": [
      "R",
      "T",
      "V"
    ],
    "text": "* Lossless transmission line\nV1 src 0 PULSE(0 1 0 100p 100p 5n 10n)\nRS src in 50\nT1 in 0 out 0 Z0=50 TD=2n\nRT out 0 50\n.end\n"
  }
];
